### ISSUE TITLE
Decode Return

### ISSUE THREAD

**Issue by dargmuesli** [fujaba/fulibYaml#1]
In regard to the following function
https://github.com/fujaba/fulibYaml/blob/de72f3aafcd1556078710d543829840a3243b859/src/main/java/org/fulib/yaml/YamlIdMap.java#L556-L562

`decode(yaml)` returns the decoded object, but `return root` returns the second parameter of this function. Why isn't it written as `return decode(yaml)` instead?
Currently, if you try to load a liverisk game that has a different name than the new game object (in the `root` object), the game is not loaded. I didn't investigate further though.

**Comment by azuendorf** [comment]
throwing an exception on wrong use now. 
This fix comes with the 2019SummerTerm release.
