### ISSUE TITLE
Enum support

### ISSUE THREAD

**Issue by Clashsoft** [fujaba/fulibYaml#12]
Add support for enum attribute value (de)serialization.

Example:

```java
enum AnimalType { DOG, CAT, MOUSE }

class Animal {
    AnimalType type;
}

Animal animal = new Animal().setType(AnimalType.DOG);

String yaml = idMap.encode(animal)
```

`yaml`:

```yaml
- animal1: Animal
  type: DOG
```

```java
Animal animal = (Animal) idMap.decode(yaml);
assert animal.getType() == AnimalType.DOG;
```

This feature is being worked on in the [`enum-support`](https://github.com/fujaba/fulibYaml/tree/enum-support) branch.

**Comment by azuendorf** [comment]
Well, I don't like Enums. 
Let us ask the product owner.

**Comment by azuendorf** [comment]
Hm, it probably needs to encode like: 
- animal1: Animal
  type: AnimalType.DOG

**Comment by Clashsoft** [comment]
The current implementation draft will use the fully qualified class name:

```yaml
- animal1: Animal
  type: org.example.AnimalType.DOG
```

This makes the implementation less reliant on context, and resolves potential ambiguity without affecting readability too much.
