### ISSUE TITLE
Events get overwritten when added too quickly

### ISSUE THREAD

**Issue by mikekluger** [fujaba/fulibYaml#8]
Using the current system time in milliseconds (line 135) as key for the `numEventMap` (line 150) causes events that are added in the same millisecond to be overwritten.

https://github.com/fujaba/fulibYaml/blob/4ef4bb04f475b91e18cd15c018d8d7c54b88a33f/src/main/java/org/fulib/yaml/EventSource.java#L123-L158

I came across this problem while loading a log file with [EventFiler#loadHistory()](https://github.com/fujaba/fulibYaml/blob/4ef4bb04f475b91e18cd15c018d8d7c54b88a33f/src/main/java/org/fulib/yaml/EventFiler.java#L26) and feeding all the events to my own datamodel and back to the `eventSource` again.

**EDIT:**
As I noticed afterwards, for my specific application the mentioned problem was easy to fix, since I just forgot to add the old timestamp to the new event object. But in general this can occur every time an event has no timestamp (e.g. when it's a completely new event where a timestamp was not defined yet) or when the timestamp is older than the last event.

**Comment by azuendorf** [comment]
Puh, nasty thing. 
Fixed it.
